### PR TITLE
Fix/quarantine broken integration tests

### PR DESCRIPTION
**Pull request by mistergaskill**
When reading the submission guidelines I realized that the integration tests were failing. I fixed what I could and disabled the others. The tests are currently failing on master due to https://github.com/Strider-CD/strider/issues/713 which https://github.com/Strider-CD/strider/pull/723 offers a fix for.

### CODE REVIEW

**Comment by knownasilya** [comment]
Since I merged the other PRs, could you re-enable the related tests? Thanks!

**Comment by mistergaskill** [comment]
Everything is now enabled and passing except the following:

./integration/github_test.js

I think this is due to a github web hook configuration issue with strider-test-robot on https://github.com/Strider-CD/strider-extension-loader

./integration/global_admin_test.js / should not be able to see all projects when not a global admin

This is due to the sign out button not being accessible on windows less then 980px wide (which my chromedriver defaults to). I'll file that as an issue since this is a real bug.

**Comment by mistergaskill** [comment]
Filed https://github.com/Strider-CD/strider/issues/727

**Comment by mistergaskill** [comment]
Ah yes, just in case anybody looks at this again - here is the error I was getting for the github tests:
```
Connect
500 AuthorizationError: The redirect_uri MUST match the registered callback URL for this application.
   at Strategy.OAuth2Strategy.authenticate (/Users/jeffgaskill/dev/strider/node_modules/strider-github/node_modules/passport-github/node_modules/passport-oauth2/lib/strategy.js:126:25)
   at attempt (/Users/jeffgaskill/dev/strider/node_modules/passport/lib/middleware/authenticate.js:341:16)
   at authenticate (/Users/jeffgaskill/dev/strider/node_modules/passport/lib/middleware/authenticate.js:342:7)
   at Layer.handle [as handle_request] (/Users/jeffgaskill/dev/strider/node_modules/express/lib/router/layer.js:82:5)
   at next (/Users/jeffgaskill/dev/strider/node_modules/express/lib/router/route.js:110:13)
   at Route.dispatch (/Users/jeffgaskill/dev/strider/node_modules/express/lib/router/route.js:91:3)
   at Layer.handle [as handle_request] (/Users/jeffgaskill/dev/strider/node_modules/express/lib/router/layer.js:82:5)
   at /Users/jeffgaskill/dev/strider/node_modules/express/lib/router/index.js:267:22
   at Function.proto.process_params (/Users/jeffgaskill/dev/strider/node_modules/express/lib/router/index.js:321:12)
   at next (/Users/jeffgaskill/dev/strider/node_modules/express/lib/router/index.js:261:10)
   at /Users/jeffgaskill/dev/strider/lib/app.js:282:5
   at Layer.handle [as handle_request] (/Users/jeffgaskill/dev/strider/node_modules/express/lib/router/layer.js:82:5)
   at trim_prefix (/Users/jeffgaskill/dev/strider/node_modules/express/lib/router/index.js:302:13)
   at /Users/jeffgaskill/dev/strider/node_modules/express/lib/router/index.js:270:7
   at Function.proto.process_params (/Users/jeffgaskill/dev/strider/node_modules/express/lib/router/index.js:321:12)
   at next (/Users/jeffgaskill/dev/strider/node_modules/express/lib/router/index.js:261:10)
```

**Comment by knownasilya** [comment]
Might be a good idea to create a separate issue for the Github tests.

**Comment by mistergaskill** [comment]
Sure, I already created an issue for the logout. I'll add this one.

**Pull request merged**
