### PR TITLE
 Project templates #876 partial fix

### PR DESCRIPTION
**Pull request by bariscicek**
- Upgrades FontAwesome to 4.4 because of 'clone' icon. And it is better to have a newer version of the font. 
- Adds cloneBranch method, which looks for existing branch name and creates a new branch with clone name.
- Adds clone icon on admin / branches to clone an existing branch.
- Fixes 'Branch added' message to 'order changed'

Notes: 
On errors UI does not show error message. But I think it is another bug so I will report and fix it on another pull request.

### CODE REVIEW

**Comment by knownasilya** [comment]
Can you squash your commits?

**Comment by bariscicek** [comment]
I dont know what you mean with that excuse my ignorance on that.

**Comment by knownasilya** [comment]
@bariscicek http://stackoverflow.com/a/5189600/483616

**Comment by bariscicek** [comment]
I think I screwed this one. It added dist files in commit while I was trying to fix tabspace issue in .jshint. 

Please let me know if you can test/merge.

**Pull request merged**
