### PR TITLE
Add password reset to the interface

### LINKED ISSUE #436: forgot password view fails
When I try to access the forgot password flow view the "Forgot you password?" link in the footer, it takes me to the `/auth/forgot` URI and returns a 500: `Error: Failed to lookup view "customer-forgot.html" in views directory "//views"`

### PR DESCRIPTION
**Pull request by knownasilya**
Closes #436 

Should work, but if anyone could test, that would rock!

strider-mailer v0.2.0 should be published for easy testing without smtp setup.

### CODE REVIEW

**Comment by macropin** [comment]
Having the password reset link hidden in the footer is bad UX. It should be added to the login form and shown when rendering a failed login message.

**Comment by knownasilya** [comment]
I agree. Will totally take a PR :wink:

**Comment by oliversalzburg** [comment]
I've moved the link in https://github.com/Strider-CD/strider/commit/8a43b9a95cdd2ff456607ebf7a26646c193001c2

@knownasilya Did I mess up anything with https://github.com/Strider-CD/strider/commit/c1cc25d64ba060617df24c4b5235205c0980bbd1 I'm not quite sure what happened there :P

**Comment by knownasilya** [comment]
Looks fine to me.

**Pull request merged**
