### PR TITLE
Add jobs quantity customization

### PR DESCRIPTION
**Pull request by nomean42**

### CODE REVIEW

**Comment by knownasilya** [comment]
Is this to increase/limit the number of jobs on the build page? If so, can we don something like `BUILDPAGE_JOBS_QUANTITY_`* instead?

**Comment by nomean42** [comment]
Im sorry, i got lost for a while. Yes its build page jobs. But how we can realise all features with only one env variable? Now we can set max and min number jobs. Enable or disable user possibility to set it in account settings. Also set default value for all users.
Are you afraid of big readme with many env variables? Or there are too many features for build page?

**Comment by knownasilya** [comment]
I would prefer them all in the UI without envs. 😃

**Comment by knownasilya** [comment]
Released in v1.11.0

**Pull request merged**
