### PR TITLE
Homepage references

### PR DESCRIPTION
**Pull request by haraldrudell**
Where is the home page?
Where is the source code?
Who is backing Strider-CD?

### CODE REVIEW

**Comment by haraldrudell** [comment]
My answers might be wrong…

**Comment by knownasilya** [comment]
I don't think FrozenRidge supports Strider any more cc @niallo 

Also, could you make sure you don't modify the white space, those are there for markdown (two spaces creates a br).

**Comment by haraldrudell** [comment]
1. It is nice to provide the canonical home page link, that appears to have changed
2. It is good to provide from where eternal support for Strider CD comes, which is someone with a cash flow, someone who is independently wealthy or a source of eternal altruism like the Apache Software Foundation

**Comment by knownasilya** [comment]
Home page can be http://stridercd.com/ which points to this repo.

I agree about the support, but there isn't anything. Feel free to find someone 👍

**Pull request closed without merging**
