### PR TITLE
Make build page fit whole page height

### PR DESCRIPTION
**Pull request by oliversalzburg**
I know this CSS might look a bit crazy, but I didn't see any other way and it looks great! :D

### CODE REVIEW

**Comment by knownasilya** [comment]
Looks like a good temporary solution

**Comment by knownasilya** [comment]
One minor issue, the "Configure" button isn't clickable on full page layout.

**Comment by oliversalzburg** [comment]
@knownasilya Argh! I'll fix that tonight.

**Comment by oliversalzburg** [comment]
@knownasilya Should be fixed in master

**Comment by knownasilya** [comment]
@oliversalzburg are you sure? I don't see any commits.

**Comment by oliversalzburg** [comment]
@knownasilya Hah. You're right. I was mixing up my remotes again ;D Should be correct now.

**Pull request merged**
