### PR TITLE
Add Strider Tutorial Series to Readme

### PR DESCRIPTION
**Pull request by marcuspoehls**
We at Future Studio created an [extensive series of guides about Strider](https://futurestud.io/blog/strider-getting-started-platform-overview/) and hope the community benefits from the tutorials. These articles cover topics like platform setup, 3rd party integrations (GitHub, GitLab, etc), continuous deployments (Heroku, SSH), notifications (email, Slack, HipChat), how to create your own Strider plugin and many more. 

We hope this help others in the community to learn more about Strider and how things are working. Additionally, this series provides a comprehensive overview of use-cases and it will help new people getting started with the platform :rocket:

### CODE REVIEW

**Comment by oliversalzburg** [comment]
Looks pretty sweet.

While briefly looking at he guides, I noticed something small you might want to address. It would be cool if the screenshot here https://futurestud.io/blog/strider-how-to-connect-with-gitlab-and-run-tests-automatically/#installstridergitlabplugin was actually pointing to an Install button ;)

**Comment by marcuspoehls** [comment]
@oliversalzburg Thanks for the hint to update the picture! Update published :)

**Comment by knownasilya** [comment]
Awesome! Thanks @marcuspoehls and team.

**Comment by bitwit** [comment]
Beautifully done @marcuspoehls . Thank you for this!

**Comment by marcuspoehls** [comment]
@oliversalzburg @knownasilya @bitwit Thanks a lot for your kind words and your support to put the link within the readme. We totally appreciate your compliments! Strider is a great project and it's always time to give back to the community. You're doing an amazing job!

**Pull request merged**
