### PR TITLE
strider.json support

### PR DESCRIPTION
**Pull request by kfatehi**
So far this is just "simple mode" check the docs

Ref #673

### CODE REVIEW

**Comment by knownasilya** [comment]
@keyvanfatehi how's this going?

**Comment by zakjan** [comment]
What is the current status? It seems to me that this PR duplicates [strider-custom](https://github.com/Strider-CD/strider-custom) plugin functionality. However it misses any GUI.

**Comment by oliversalzburg** [comment]
@zakjan `strider.json` functionality is not exclusive to strider-custom. It already affects the whole application. I wrote something about that somewhere…

**Comment by sebas5384** [comment]
Just a thought:
It's just the automated test that is needed? if so, then maybe some test directions could help anyone that could want to contribute.

**Comment by knownasilya** [comment]
Closing this. See strider-custom's README for how to use the current strider.json config. It's already pretty powerful and I don't think this is necessary.

**Pull request closed without merging**
